version: '3.8'

services:
  french-business-mcp:
    build:
      context: .
      dockerfile: Dockerfile.multistage
    container_name: french-business-mcp-server
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - mcp-network
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mcp-network:
    driver: bridge